// <auto-generated/>
using System;

namespace Telegram.Api.TL.Methods.Account
{
	/// <summary>
	/// RCP method account.updateStatus.
	/// Returns <see cref="Telegram.Api.TL.TLBool"/>
	/// </summary>
	public partial class TLAccountUpdateStatus : TLObject
	{
		public Boolean Offline { get; set; }

		public TLAccountUpdateStatus() { }
		public TLAccountUpdateStatus(TLBinaryReader from)
		{
			Read(from);
		}

		public override TLType TypeId { get { return TLType.AccountUpdateStatus; } }

		public override void Read(TLBinaryReader from)
		{
			Offline = from.ReadBoolean();
		}

		public override void Write(TLBinaryWriter to)
		{
            //try
            //{
            //    if (Helpers.SettingsHelper.GetValue("ghost") == null || (bool)Helpers.SettingsHelper.GetValue("ghost") == false)
            //    {
            //        to.Write(0x6628562C);
            //        to.Write(Offline);
            //    } else
            //    {
            //        to.Write(0x6628562C);
            //        to.Write(true);
            //    }
            //}
            //catch (Exception) {
            //    to.Write(0x6628562C);
            //    to.Write(Offline);
            //};
            to.Write(0x6628562C);
			to.Write(Offline);
		}
	}
}